---
title: "flat_additional.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(shiny)
```

```{r development-1}
pkgload::load_all()
```

# Create icon

```{r function-my_fun}
#' create_icon
#'
#' @param href url to follow when click
#' @param src img to use as icon
#'
#' @importFrom glue glue
#' @importFrom htmltools htmlTemplate
#'
#' @noRd
create_icon <- function(href, src) {
  htmlTemplate(
    filename = app_sys("app", "www", "templates", "thinkr", "icon.html"),
    href = href,
    src = src
  )
}
```

```{r examples-my_fun}
create_icon("plop.fr", "www/icons/linkedin.png")
```

```{r tests-my_fun}
test_that("create_icon works", {
  code <- create_icon("plop.fr", "www/icons/linkedin.png")
  expect_true(inherits(code, "shiny.tag.list"))
  expect_snapshot(code)
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_utils.Rmd",
  vignette_name = "Go further",
  open_vignette = FALSE,
  check = FALSE
)
unlink(here::here("vignettes", "go-further.Rmd"))
devtools::check()
```

