---
title: "flat_additional.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(shiny)
```

```{r development-1}
pkgload::load_all()
```

# Create icon

```{r function-my_fun}
#' create_icon
#'
#' @param href url to follow when click
#' @param src img to use as icon
#'
#' @importFrom glue glue
#' @importFrom shiny HTML
#'
#' @noRd
create_icon <- function(href, src) {
  
  if (!is.null(href)) {
    if (href != "") {
      htmlTemplate(
        filename = app_sys("app", "www", "templates", "thinkr", "icon.html"),
        href = href,
        src = src
      )  
    } 
  }
}
```

```{r examples-my_fun}
create_icon("plop.fr", "www/icons/linkedin.png")
```

```{r tests-my_fun}
test_that("create_icon works", {
  code <- create_icon("plop.fr", "www/icons/linkedin.png")
  expect_true(inherits(code, "shiny.tag.list"))
  expect_snapshot(code)
  
  expect_null(create_icon("", "www/icons/linkedin.png"))
})
```

# Create accordion

See Boostrap documentation for more details:
https://getbootstrap.com/docs/5.1/components/accordion/

```{r function-accordion}
#' accordion
#'
#' Create an accordion
#'
#' @param id id of the accordion for html
#' @param items a taglist of accordion items
#'
#' @return shiny.tag
#'
#' @noRd
accordion <- function(id, items) {
  tags$div(
    class = "accordion",
    id = id,
    items
  )
}
```

```{r examples-accordion}
accordion(
  id = "myaccordion",
  items = tagList()
)
```

```{r tests-accordion}
test_that("accordion works", {
  acc <- accordion(id = "myaccordion", items = tagList())
  expect_true(inherits(acc, "shiny.tag"))
  expect_snapshot(acc)
})
```

# Create accordion item

```{r function-accordion-item}
#' accordion item
#'
#' Create an accordion item
#'
#' @param accordion_id id of the accordion
#' @param item_id id of the accordion item
#' @param item_header header or title to display
#' @param open accordion item is open or collasped
#' @param button_id id of the button
#' @param ... content to display in the accordion item body
#'
#' @return shiny.tag
#'
#' @noRd
accordion_item <- function(accordion_id,
                           item_id,
                           item_header,
                           open,
                           button_id,
                           ...) {
  tags$div(
    class = "accordion-item",
    h2(
      class = "accordion-header",
      id = item_id,
      tags$button(
        class = ifelse(
          isTRUE(open),
          "accordion-button",
          "accordion-button collapsed"
        ),
        type = "button",
        `data-bs-toggle` = "collapse",
        `data-bs-target` = paste0("#", button_id),
        `aria-expanded` = ifelse(isTRUE(open), "true", "false"),
        `aria-controls` = button_id,
        item_header
      )
    ),
    tags$div(
      class = ifelse(
        isTRUE(open),
        "accordion-collapse collapse show",
        "accordion-collapse collapse"
      ),
      `aria-labelledby` = item_id,
      `data-bs-parent` = paste0("#", accordion_id),
      id = button_id,
      tags$div(
        class = "accordion-body",
        ...
      )
    )
  )
}
```

```{r examples-accordion-item}
accordion_item(
  accordion_id = "accordion",
  item_id = "accordition-item",
  item_header = "Title",
  buttonid = "itemButton",
  p("This is a text"),
  p("Inside an accordion item")
)
```

```{r tests-accordion-item}
test_that("accordion_item works", {
  item <- accordion_item(
    accordion_id = "accordion",
    item_id = "accordition-item",
    item_header = "Title",
    buttonid = "itemButton",
    p("This is a text"),
    p("Inside an accordion item")
  )
  expect_true(inherits(item, "shiny.tag"))
  expect_snapshot(item)
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_additional.Rmd",
  vignette_name = "Go further",
  open_vignette = FALSE,
  check = FALSE
)
unlink(here::here("vignettes", "go-further.Rmd"))
devtools::check()
```

