# WARNING - Generated by {fusen} from /dev/flat_additional.Rmd: do not edit by hand

test_that("accordion works", {
  acc <- accordion(id = "myaccordion", items = tagList())
  expect_true(inherits(acc, "shiny.tag"))
  expect_snapshot(acc)
})
