# Generated by fusen: do not edit by hand

test_that("accordion works", {
  acc <- accordion(id = "myaccordion", items = tagList())
  expect_true(inherits(acc, "shiny.tag"))
  expect_snapshot(acc)

  acc2 <- carousel(
    id = "carouselExampleIndicators",
    carousel_item = tagList(
      carousel_item(
        is_active = TRUE,
        tags$img(src = "...")
      ),
      carousel_item(
        is_active = FALSE,
        tags$img(src = "...")
      )
    )
  )
  expect_true(inherits(acc2, "shiny.tag"))
  expect_snapshot(acc2)
})
