# Generated by fusen: do not edit by hand

test_that("carousel_item works", {
  item_true <- carousel_item(is_active = TRUE, img(src = "..."))
  item_false <- carousel_item(is_active = FALSE, img(src = "..."))
  expect_true(inherits(item_true, "shiny.tag"))
  expect_snapshot(item_true)
  expect_snapshot(item_false)
})
