# Generated by fusen: do not edit by hand

test_that("create_icon works", {
  code <- create_icon("plop.fr", "www/icons/linkedin.png")
  expect_true(inherits(code, "shiny.tag.list"))
  expect_snapshot(code)
})
