# WARNING - Generated by {fusen} from /dev/flat_additional.Rmd: do not edit by hand

test_that("accordion_item works", {
  item <- accordion_item(
    accordion_id = "accordion",
    item_id = "accordition-item",
    item_header = "Title",
    buttonid = "itemButton",
    p("This is a text"),
    p("Inside an accordion item")
  )
  expect_true(inherits(item, "shiny.tag"))
  expect_snapshot(item)
})
