# Generated by fusen: do not edit by hand

test_that("carousel_indicator works", {
  indicator <- carousel_indicator(
    id = "indic",
    carousel_item = carousel_item(
      is_active = TRUE,
      tags$img(src = "...")
    ),
    pos = 1
  )
  expect_true(inherits(indicator, "shiny.tag"))
  expect_snapshot(indicator)
})
