# Generated by fusen: do not edit by hand

#' accordion item
#'
#' Create an accordion item
#'
#' @param accordion_id id of the accordion
#' @param item_id id of the accordion item
#' @param item_header header or title to display
#' @param open accordion item is open or collasped
#' @param button_id id of the button
#' @param ... content to display in the accordion item body
#'
#' @return shiny.tag
#'
#' @noRd
#' @examples
#' accordion_item(
#'   accordion_id = "accordion",
#'   item_id = "accordition-item",
#'   item_header = "Title",
#'   buttonid = "itemButton",
#'   p("This is a text"),
#'   p("Inside an accordion item")
#' )
accordion_item <- function(accordion_id,
                           item_id,
                           item_header,
                           open,
                           button_id,
                           ...) {
  tags$div(
    class = "accordion-item",
    h2(
      class = "accordion-header",
      id = item_id,
      tags$button(
        class = ifelse(
          isTRUE(open),
          "accordion-button",
          "accordion-button collapsed"
        ),
        type = "button",
        `data-bs-toggle` = "collapse",
        `data-bs-target` = paste0("#", button_id),
        `aria-expanded` = ifelse(isTRUE(open), "true", "false"),
        `aria-controls` = button_id,
        item_header
      )
    ),
    tags$div(
      class = ifelse(
        isTRUE(open),
        "accordion-collapse collapse show",
        "accordion-collapse collapse"
      ),
      `aria-labelledby` = item_id,
      `data-bs-parent` = paste0("#", accordion_id),
      id = button_id,
      tags$div(
        class = "accordion-body",
        ...
      )
    )
  )
}
