# Generated by fusen: do not edit by hand

#' accordion
#'
#' Create an accordion
#'
#' @param id id of the accordion for html
#' @param items a taglist of accordion items
#'
#' @return shiny.tag
#'
#' @export
#' @examples
#' accordion(
#'   id = "myaccordion",
#'   items = tagList()
#' )
#' 
#' accordion(
#'   id = "myaccordion",
#'   items = tagList(
#'     accordion_item(
#'       accordion_id = "myaccordion",
#'       item_id = "accordition-item1",
#'       item_header = "Title 1",
#'       buttonid = "itemButton1",
#'       tags$p("This is a text"),
#'       tags$p("Inside an accordion item")
#'     ),
#'     accordion_item(
#'       accordion_id = "myaccordion",
#'       item_id = "accordition-item2",
#'       item_header = "Title 2",
#'       buttonid = "itemButton2",
#'       tags$p("This is a text"),
#'       tags$p("Inside an accordion item")
#'     )
#'   )
#' )
accordion <- function(id, items) {
  tags$div(
    class = "accordion",
    id = id,
    items
  )
}
