# Generated by fusen: do not edit by hand

#' accordion
#'
#' Create an accordion
#'
#' @param id id of the accordion for html
#' @param items a taglist of accordion items
#'
#' @return shiny.tag
#'
#' @noRd
#' @examples
#' accordion(
#'   id = "myaccordion",
#'   items = tagList()
#' )
accordion <- function(id, items) {
  tags$div(
    class = "accordion",
    id = id,
    items
  )
}
