# Generated by fusen: do not edit by hand

#' create a carousel indicator
#'
#' @param id id of the carousel
#' @param carousel_item carousel_item()
#' @param pos carousel item position in the taglist
#'
#' @importFrom htmltools tagGetAttribute tagAppendAttributes
#'
#' @return shiny.tag
#' @export
#' @examples
#' carousel_indicator(
#'   id = "indic",
#'   carousel_item = carousel_item(
#'     is_active = TRUE,
#'     img(src = "...")
#'   ),
#'   pos = 1
#' )
carousel_indicator <- function(id, carousel_item, pos) {
  button <- tags$button(
    type = "button",
    `data-bs-target` = paste0("#", id),
    `data-bs-slide-to` = pos - 1,
    `aria-label` = paste0("Slide ", pos)
  )

  if (tagGetAttribute(carousel_item, "class") == "carousel-item active") {
    button <- tagAppendAttributes(button, class = "active")
    button <- tagAppendAttributes(button, `aria-current` = "true")
  }
  return(button)
}
