# Generated by fusen: do not edit by hand

#' create a carousel item
#'
#' @param is_active is the carousel item active
#' @param ... content to display in the carousel body
#'
#' @return shiny.tag
#' @export
#' @examples
#' carousel_item(
#'   is_active = TRUE,
#'   tags$img(src = system.file(
#'     "app", "www", "templates", "thinkr", "assets", "logo.jpg",
#'     package = "signature"
#'   ))
#' )
carousel_item <- function(is_active, ...) {
  tags$div(
    class = ifelse(isTRUE(is_active), "carousel-item active", "carousel-item"),
    ...
  )
}
