# Generated by fusen: do not edit by hand

#' create a carousel
#'
#' @param id id of the carousel for html
#' @param carousel_items a taglist of carousel_item()
#'
#' @importFrom purrr map2
#'
#' @return shiny.tag
#'
#' @export
#' @examples
#' carousel(
#'   id = "carouselExample",
#'   tagList()
#' )
#' 
#' carousel(
#'   id = "carouselExampleIndicators",
#'   carousel_item = tagList(
#'     carousel_item(
#'       is_active = TRUE,
#'       tags$img(src = system.file(
#'         "app", "www", "templates", "thinkr", "assets", "logo.jpg",
#'         package = "signature"
#'       ))
#'     ),
#'     carousel_item(
#'       is_active = FALSE,
#'       tags$img(src = system.file(
#'         "app", "www", "templates", "thinkr", "assets", "logo.jpg",
#'         package = "signature"
#'       ))
#'     )
#'   )
#' )
carousel <- function(id, carousel_items) {
  carousel_indicators <- carousel_items %>%
    map2(
      seq_along(.),
      ~ carousel_indicator(id = id, carousel_item = .x, pos = .y)
    )

  tags$div(
    id = id,
    class = "carousel slide",
    `data-bs-ride` = "carousel",
    tags$div(
      class = "carousel-indicators",
      carousel_indicators
    ),
    tags$div(
      class = "carousel-inner",
      carousel_items
    ),
    tags$button(
      class = "carousel-control-prev",
      type = "button",
      `data-bs-target` = paste0("#", id),
      `data-bs-slide` = "prev",
      tags$span(
        class = "carousel-control-prev-icon",
        `aria-hidden` = "true"
      ),
      tags$span(
        class = "visually-hidden",
        "Previous"
      )
    ),
    tags$button(
      class = "carousel-control-next",
      type = "button",
      `data-bs-target` = paste0("#", id),
      `data-bs-slide` = "next",
      tags$span(
        class = "carousel-control-next-icon",
        `aria-hidden` = "true"
      ),
      tags$span(
        class = "visually-hidden",
        "Next"
      )
    )
  )
}
