# WARNING - Generated by {fusen} from /dev/flat_additional.Rmd: do not edit by hand

#' create_icon
#'
#' @param href url to follow when click
#' @param src img to use as icon
#'
#' @importFrom glue glue
#' @importFrom shiny HTML
#'
#' @noRd
#' @examples
#' create_icon("plop.fr", "www/icons/linkedin.png")
create_icon <- function(href, src) {
  
  if (href != "") {
    htmlTemplate(
      filename = app_sys("app", "www", "templates", "thinkr", "icon.html"),
      href = href,
      src = src
    )  
  }
}
